name: Auto-generate domain rules

on:
  push:
    paths:
      - 'raw/*.txt'
      - 'json/*.json'
      - 'convert_txt_to_json.py'

  workflow_dispatch:  # Позволяет вручную запускать из GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install -r requirements.txt || true  # если нужен requirements.txt

      - name: Run convert_txt_to_json.py
        run: |
          mkdir -p json
          python3 convert_txt_to_json.py

      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/deb-install.sh | bash

      - name: Save old JSON for comparison
        run: |
          mkdir -p old_json old_srs
          cp -a json/*.json old_json/ || true
          cp -a srs/*.srs old_srs/ || true

      - name: Compile JSON to SRS only if changed
        run: |
          mkdir -p srs
          for json_file in json/*.json; do
            filename=$(basename "$json_file" .json)
            old_file="old_json/${filename}.json"
            if ! cmp -s "$json_file" "$old_file"; then
              echo "JSON changed: $filename.json"
              sing-box rule-set compile "$json_file" -o "srs/${filename}.srs"
            else
              echo "No changes in $filename.json; skipping compile"
              cp "old_srs/${filename}.srs" "srs/${filename}.srs" 2>/dev/null || true
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add raw/*.txt json/*.json srs/*.srs
          git diff --cached --quiet || git commit -m "chore: auto-compile domain lists and rule-sets"
          git push
